$(function(){
	$(".head_pic").click(function(){
		if($(".drop_border").css("display")=="none"){
			$(".drop_border").css("display","block");
		}else{
			$(".drop_border").css("display","none");
		}
	});
			});